/*
 * generated by Xtext
 */
package org.xtext.hipie.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HIPIEUiModule extends org.xtext.hipie.ui.AbstractHIPIEUiModule {
	public HIPIEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	 public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
		 return HIPIEHighlightingConfig.class;
		 }
		 
	 public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		 return HIPIEHighlightingCalc.class;
		 }
		 
	 public Class<? extends LanguageRootPreferencePage> bindLanguageRootPreferencePage() {
		 return HIPIEPrefPage.class;
		 }
}

