/*
 * generated by Xtext
 */
package org.xtext.hipie;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.xtext.hipie.custom.OutputConfigs;

import com.google.inject.Binder;
import com.google.inject.Singleton;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HIPIERuntimeModule extends org.xtext.hipie.AbstractHIPIERuntimeModule {
	  @Override
	  public void configure(Binder binder) {
	    super.configure(binder);
	    binder.bind(IOutputConfigurationProvider.class)
	        .to(OutputConfigs.class)
	        .in(Singleton.class);
	  }
}
